name: deploy to gh-pages

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      working-directory: ./na-log
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Copy posts
        run: cp -r -f posts ${{ env.working-directory }}

      - name: Copy public
        run: cp -r -f public ${{ env.working-directory }}
          
      - name: Check node-modules
        uses: actions/cache@v3
        id: node-modules-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        working-directory: ${{ env.working-directory }}
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build React
        working-directory: ${{ env.working-directory }}
        run: |
           echo $GITHUB_REPOSITORY |
           yarn build
        env:
          GITHUB_REPOSITORY: $GITHUB_REPOSITORY

      - name: Deploy to 'gh-pages' branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.working-directory }}/out
