name: deploy to gh-pages

on:
  push:
    branches: ['main']

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      working-directory: ./na-log
      baseUrl: /na-log
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Copy posts
        run: cp -r -f posts ${{ env.working-directory }}

      - name: Copy public
        run: cp -r -f public ${{ env.working-directory }}

      - name: test
        run: |
          cd|
          dir

      - name: test
        working-directory: ${{ env.working-directory }}
        run: |
          cd|
          dir
          
      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Build React
        working-directory: ${{ env.working-directory }}
        run: yarn build
        env:
          basePath: na-log-test
          
      - name: Deploy to 'gh-pages' branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.working-directory }}/out
